services:
  db:
    image: mongo:4.4.6
    volumes:
      - ./data:/data/db

  code-runner:
    image: 127.0.0.1:5000/code-runner
    build: ./code-runner

  web:
    depends_on:
      - db
      - code-runner

    image: 127.0.0.1:5000/web
    build: .

    ports:
      - "${PORT:?error}:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SERVER_URL=http://10.212.173.135
      - DATABASE_URL=mongodb://db:27017/kode-kamp
      - CODE_RUNNER_URL=http://code-runner:3000
      - JWT_SECRET=awdawd
# TODO docker secrets
