stages: # List of stages for jobs, and their order of execution
  - build
  - test
  # - deploy

image: node:20.17.0

build site:
  stage: build
  script:
    - cd backend
    - npm install
    - npm run build
  cache:
    key:
      files:
        - ./backend/package-lock.json
      prefix: npm
    paths:
      - ./backend/node_modules/
  rules:
    - when: always

test site:
  stage: test
  script:
    - cd backend
    - npm install
    - npm run test
  cache:
    key:
      files:
        - ./backend/package-lock.json
      prefix: npm
    paths:
      - ./backend/node_modules/
  rules:
    - when: always
