title = "Umferð"
license = "Creative Commons License (cc by)"
description = '''
 <p>Traffic jams are a major problem in larger cities like Njú
    Jork and Síattúl, especially during rush hour.</p> <p>In a traffic jam there are many cars with very little
    spacing between them, and they are not moving particularly
    fast. To simplify things we will assume that traffic is divided
    into <em>lanes</em> and each lane consists of <span class=\"tex2jax_process\">$m$</span> <em>cells</em>. Each cell can
    contain at most <span class=\"tex2jax_process\">$1$</span> car,
    but a cell can also be empty.</p> 

    <p>The length <span class=\"tex2jax_process\">$m$</span> of the
    lanes, the number of lanes <span class=\"tex2jax_process\">$n$</span> and a textual description of each
    cell, such that a cell containing a car is denoted <tt class=\"ttfamily\">#</tt> and an empty cell is denoted <tt class=\"ttfamily\">.</tt>, is given.</p>
    
    <p>The task at hand is to calculate the proportion of empty
    cells, as a number between <span class=\"tex2jax_process\">$0$</span> and <span class=\"tex2jax_process\">$1$</span>, inclusive.</p>
'''

input = '''<p>The first line of the input contains a single integer
    <span class=\"tex2jax_process\">$m$</span>, the number of cells
    per lane. The next line contains a single integer <span class=\"tex2jax_process\">$n$</span>, the number of lanes. Next there
    are <span class=\"tex2jax_process\">$n$</span> lines. Each line
    contains <span class=\"tex2jax_process\">$m$</span> letters, each
    being either <tt class=\"ttfamily\">.</tt> or <tt class=\"ttfamily\">#</tt>.</p>'''

output = '''
<p>Print the proportion of empty cells as a value from
    <span class=\"tex2jax_process\">$0$</span> to <span class=\"tex2jax_process\">$1$</span>.</p><p>The output is considered correct if its relative or absolute
    error is at most <span class=\"tex2jax_process\">$10^{-5}$</span>. This means that the exact
    number of digits after the decimal point does not matter as
    long as the value is accurate enough.</p>
'''

template = '''
const input = readline();

// console.log(output);
'''


[[attribution]]
name = "Hannes Kristján Hannesson"
url = "https://open.kattis.com/problem-authors/Hannes%20Kristj%C3%A1n%20Hannesson"

[[attribution]]
name = "Arnar Bjarni Arnarson"
url = "https://open.kattis.com/problem-authors/Arnar%20Bjarni%20Arnarson"

[[sampleTests]]
input = ["2", "1", ".#"]
output = ["0.5"]

[[sampleTests]]
input = ["4", "2", "#.#.", ".###"]
output = ["0.375"]

[[sampleTests]]
input =[ "2", "1", ".#"]
output = ["0.5"]

[[sampleTests]]
input =[ "4", "2", "#.#.", ".###"]
output =[ "0.375"]


[[tests]]
input = ["2", "1", ".#"]
output = ["0.5"]

[[tests]]
input = ["4", "2", "#.#.", ".###"]
output = ["0.375"]

[[tests]]
input =[ "2", "1", ".#"]
output = ["0.5"]

[[tests]]
input =[ "4", "2", "#.#.", ".###"]
output =[ "0.375"]

