const PORT = process.env.PORT || 3000;
const MAX_PLAYERS_PR_GAME : number = 4;
const COUNTDOWN_LENGTH_SECONDS : number = 5;
const TIME_AT_ENDSCREEN_SECONDS : number = 60;
const GAME_LENGTH_MINUTES : number = 15;
const LOBBY_TIMER_SECONDS : number = 30;
const GAME_MODES : string[] = ["First to finish"];
const CODE_RUNNER_URL : string = "https://code-runner-small-sky-5409.fly.dev/execute";

const randomUsernames: string[] = [
    "ShadowHunter",
    "LightningBolt",
    "MaverickX",
    "SilentStorm",
    "NightWolf",
    "PixelWizard",
    "ThunderStrike",
    "GhostRider",
    "BlazePhoenix",
    "IronHeart",
    "CyberNinja",
    "LunarEclipse",
    "RapidFire",
    "NeonTiger",
    "WildCard",
    "DarkPhantom",
    "FrostByte",
    "EpicSurge",
    "StormBreaker",
    "VortexMaster",
    "SolarFlare",
    "VenomFang",
    "CrimsonShade",
    "SteelFalcon",
    "HyperViper",
    "ShadowRaven",
    "GalacticWolf",
    "SilverScorpion",
    "BlizzardFury",
    "ChaosKnight",
    "NebulaWraith",
    "DragonSlayer",
    "AtomicBlaze",
    "SpectralBlade",
    "DarkInferno",
    "IronShadow",
    "ZenithWarrior",
    "TidalSurge",
    "OmegaStrike",
    "CosmicPhantom",
    "VoidHunter",
    "StormRider",
    "ThunderWolf",
    "PhantomSpecter",
    "IronTiger",
    "LightningFury",
    "SkyBreaker",
    "EclipseWarrior",
    "FlameRider",
    "LunarKnight",
    "NeonViper",
    "NovaSurge",
    "DarkRider",
    "SilverPhoenix",
    "InfernoKnight",
    "ViperShadow",
    "WildStrike",
    "GhostBlade",
    "CyberPhantom",
    "FrostTiger",
    "StormChaser",
    "ShadowPhoenix",
    "RapidViper",
    "ThunderBlade",
    "VenomRider",
    "BlazeTiger",
    "IronKnight",
    "NeonShadow",
    "FrostViper",
    "DarkTiger",
    "VortexRider",
    "CosmicKnight",
    "ThunderViper",
    "ShadowFury",
    "SilverBlade",
    "BlazeRider",
    "LunarFury",
    "NebulaKnight",
    "WildPhantom",
    "StormViper"
];

export {
    randomUsernames,
    PORT,
    MAX_PLAYERS_PR_GAME,
    COUNTDOWN_LENGTH_SECONDS,
    TIME_AT_ENDSCREEN_SECONDS,
    GAME_LENGTH_MINUTES,
    LOBBY_TIMER_SECONDS,
    GAME_MODES,
    CODE_RUNNER_URL
}