title = "ABC"
license = "Creative Commons License (cc by)"

attribution = [
]

description = '''
<p>You will be given three integers <span class="tex2jax_process">$A$</span>, <span class="tex2jax_process">$B$</span> and <span class="tex2jax_process">$C$</span>. The numbers will not be given in
    that exact order, but we do know that <span class="tex2jax_process">$A$</span> is less than <span class="tex2jax_process">$B$</span> and <span class="tex2jax_process">$B$</span> less than <span class="tex2jax_process">$C$</span>. In order to make for a more
    pleasant viewing, we want to rearrange them in a given
    order.</p>
'''

input = '''
<p>The first line contains the three positive integers
    <span class="tex2jax_process">$A$</span>, <span class="tex2jax_process">$B$</span> and <span class="tex2jax_process">$C$</span>, not necessarily in that order.
    The three numbers will be less than or equal to <span class="tex2jax_process">$100$</span>.</p>
<p>The second line contains three uppercase letters ’<tt class="ttfamily">A</tt>’, ’<tt class="ttfamily">B</tt>’ and
    ’<tt class="ttfamily">C</tt>’ (with no spaces between them)
    representing the desired order.</p>
'''

output = '''
<p>Output <span class="tex2jax_process">$A$</span>,
    <span class="tex2jax_process">$B$</span> and <span class="tex2jax_process">$C$</span> in the desired order on a single
    line, separated by single spaces.</p>
'''

template = '''
let input = readline();

// console.log(output);
'''

sampleTests = [
  { input = ['1 5 3', 'ABC'], output = ['1 3 5'] },
  { input = ['6 4 2', 'CAB'], output = ['6 2 4'] },
]

tests = [
  { input = ['1 5 3', 'ABC'], output = ['1 3 5'] },
  { input = ['6 4 2', 'CAB'], output = ['6 2 4'] },
]
