title = "Cold-puter Science"
license = "Creative Commons License (cc by)"

attribution = [
]

description = '''
<p>We’re not going to sugar-coat it: Chicago’s winters can be
    rough. The temperatures sometimes dip to uncomfortable levels
    and, after last year’s “polar vortex”, the University of
    Chicago Weather Service wants to find out exactly how bad the
    winter was. More specifically, they are interested in knowing
    the total number of days in which the temperature was below
    zero degrees Celsius.</p>
'''

input = '''
<p>The input is composed of two lines. The first line contains
    a single positive integer <span class="tex2jax_process">$n$</span> (<span class="tex2jax_process">$1
    \le n \le 100$</span>) that specifies the number of
    temperatures collected by the University of Chicago Weather
    Service. The second line contains <span class="tex2jax_process">$n$</span> temperatures, each separated by a
    single space. Each temperature is represented by an integer
    <span class="tex2jax_process">$t$</span> (<span class="tex2jax_process">$-1\, 000\, 000 \le t \le 1\, 000\,
    000$</span>)</p>
'''

output = '''
<p>You must print a single integer: the number of temperatures
    strictly less than zero.</p>
'''

template = '''
let input = readline();

// console.log(output);
'''

sampleTests = [
  { input = ['3', '5 -10 15'], output = ['1'] },
  { input = ['5', '-14 -5 -39 -5 -7'], output = ['5'] },
]

tests = [
  { input = ['3', '5 -10 15'], output = ['1'] },
  { input = ['5', '-14 -5 -39 -5 -7'], output = ['5'] },
]
