title = "Finding An A"
license = "Creative Commons License (cc by)"

attribution = [
  { name = "Zachary Friggstad", url = "https://open.kattis.com/problem-authors/Zachary%20Friggstad" },
]

description = '''
<p>In this problem, you are given a single string <span class="tex2jax_process">$s$</span> that is guaranteed to contain the
    letter <tt class="ttfamily">a</tt>.</p>

<p>You should output the suffix of <span class="tex2jax_process">$s$</span> that begins with the first
    occurrence of the letter <span class="tex2jax_process">$a$</span>. Namely, if <span class="tex2jax_process">$s$</span> consists of characters
    <span class="tex2jax_process">$s_1s_2\ldots s_ n$</span> and
    <span class="tex2jax_process">$i$</span> is the first index
    with <span class="tex2jax_process">$s_ i = \texttt{a}$</span>,
    then you should output the string <span class="tex2jax_process">$s_ is_{i+1}\ldots s_ n$</span>.</p>

<p>Why do you want to do this? To solve a problem in the
    contest!</p>
'''

input = '''
<p>Input consists of a single line containing a single string
    <span class="tex2jax_process">$s$</span> whose length is
    between <span class="tex2jax_process">$1$</span> and
    <span class="tex2jax_process">$1\, 000$</span>. The string is
    composed of lowercase letters with no spaces. You are
    guaranteed the letter <tt class="ttfamily">a</tt> appears at
    least once in <span class="tex2jax_process">$s$</span>.</p>
'''

output = '''
<p>Output the suffix of <span class="tex2jax_process">$s$</span> that begins with the first
    occurrence of the letter <tt class="ttfamily">a</tt>.</p>
'''

template = '''
let input = readline();

// console.log(output);
'''

sampleTests = [
  { input = ['banana'], output = ['anana'] },
  { input = ['polarbear'], output = ['arbear'] },
  { input = ['art'], output = ['art'] },
]

tests = [
  { input = ['banana'], output = ['anana'] },
  { input = ['polarbear'], output = ['arbear'] },
  { input = ['art'], output = ['art'] },
]
