title = "Kiki Boba"
license = "Creative Commons License (cc by)"
description = '''
<p>“<tt class=\"ttfamily\">Kiki</tt>” and “<tt class=\"ttfamily\">boba</tt>” form a fascinating sound-symbolic
    connection, where people spontaneously associate sharp sounds
    like “<tt class=\"ttfamily\">kiki</tt>” with jagged shapes and
    softer sounds like “<tt class=\"ttfamily\">boba</tt>” with
    rounder shapes. This reveals an underlying link between sounds
    and visual properties, providing insight into how our brains
    intuitively create meaning and associations.</p> 
    <p>Fergus has long held a keen interest in phonetics, and based
    on this sound-symbolic connection, he has developed a theory!
    He believes that all words can be categorized into 4
    categories. In other words, each word is either a word
    corresponding to the figure on the left, like “<tt class=\"ttfamily\">kiki</tt>”, or a word corresponding to the figure on
    the right, like “<tt class=\"ttfamily\">boba</tt>”, or a word
    that is a combination of both, or a word that is none of the
    aforementioned alternatives.</p>
    
     <p>Fergus determines that a word belongs to a category
    according to the following rules: If there are more “<tt class=\"ttfamily\">b</tt>” than “<tt class=\"ttfamily\">k</tt>” in the
    word, then the word is a “<tt class=\"ttfamily\">boba</tt>” word.
    If there are more “<tt class=\"ttfamily\">k</tt>” than
    “<tt class=\"ttfamily\">b</tt>” in the word, then the word is a
    “<tt class=\"ttfamily\">kiki</tt>” word. If the word contains an
    equal number of “<tt class=\"ttfamily\">b</tt>” and “<tt class=\"ttfamily\">k</tt>”, then Fergus calls it a “<tt class=\"ttfamily\">boki</tt>” word. These rules hold with one
    exception: If there are no “<tt class=\"ttfamily\">b</tt>” and
    “<tt class=\"ttfamily\">k</tt>” in the word, the word is neither
    close to a “<tt class=\"ttfamily\">boba</tt>” word nor a
    “<tt class=\"ttfamily\">kiki</tt>” word. In this case, Fergus
    refers to the word as a “<tt class=\"ttfamily\">none</tt>”
    word.</p> 
    
    <p>Help Fergus write a program that, given a word, can
    categorize the word according to Fergus’ rules.</p> 
'''

input = '''
<p>The only line of the input contains a string consisting of
    characters “<tt class=\"ttfamily\">a</tt>”-“<tt class=\"ttfamily\">z</tt>”, the word that Fergus wants to
    categorize.</p>
'''
output = '''
<p>Print a category: either “<tt class=\"ttfamily\">boba</tt>”,
    “<tt class=\"ttfamily\">kiki</tt>”, “<tt class=\"ttfamily\">boki</tt>” or “<tt class=\"ttfamily\">none</tt>”,
    according to Fergus’ rules stated above. There is always one
    category that fits each word.</p>
'''

template = '''
const input = readline();

// console.log(output);
'''


[[attribution]]
name = "Harry Zhang"
url = "https://open.kattis.com/problem-authors/Harry%20Zhang"

[[sampleTests]]
input = ["boba"]
output = ["boba"]

[[sampleTests]]
input = ["kiki"]
output = ["kiki"]

[[sampleTests]]
input = ["kobra"]
output = ["boki"]

[[sampleTests]]
input = ["ljus"]
output = ["none"]


[[tests]]
input = ["boba"]
output = ["boba"]

[[tests]]
input = ["kiki"]
output = ["kiki"]

[[tests]]
input = ["kobra"]
output = ["boki"]

[[tests]]
input = ["ljus"]
output = ["none"]

